apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
namespace: dev
images:
- name: andor-familybudget
  newName: adasit/andor-familybudget
  newTag: 4c2b0bdb
