apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
namespace: prod
images:
- name: andor-familybudget
  newName: adasit/andor-familybudget
  newTag: 31f6edb472aff7a5fa91a2021a15f9b6a9876710
