version: '3.8'

services:
  app:
    container_name: andor
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    ports:
      - 5000:5000
      - 5001:5001
    networks:
      - custom-budget

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - custom-budget

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 9091:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=P@55w0rd
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    networks:
      - custom-budget

volumes:
  prom_data:
networks:
  custom-budget:
    driver: bridge
