<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>1ac6b2e3-e01d-4049-a803-70ad71331018</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.Functions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Assets\Andor.Assets.Service\Andor.Assets.Service.csproj" />
    <ProjectReference Include="..\..\..\Budget\Andor.Accounts.Service\Andor.Accounts.Service.csproj" />
    <ProjectReference Include="..\..\..\Communications\Andor.Communications.External\Andor.Communications.External.csproj" />
    <ProjectReference Include="..\..\..\Communications\Andor.Communications.Service\Andor.Communications.Service.csproj" />
    <ProjectReference Include="..\..\..\Goals\Andor.Goals.Service\Andor.Goals.Service.csproj" />
    <ProjectReference Include="..\..\..\Onboarding\Andor.Onboarding.Service\Andor.Onboarding.Service.csproj" />
    <ProjectReference Include="..\..\Configurations\Andor.Configurations.Service\Andor.Configurations.Service.csproj" />
    <ProjectReference Include="..\..\ReverseProxy\Andor.Admin.ReverseProxy.Yarp\Andor.Admin.ReverseProxy.Yarp.csproj" />
    <ProjectReference Include="..\..\Users\Andor.Users.WebApi\Andor.Users.WebApi.csproj" />
    <ProjectReference Include="..\..\..\Users\Andor.Users.Service\Andor.Users.Service.csproj" />
  </ItemGroup>

</Project>
